<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
import numpy as np

# randomly initialize weights
weights = np.random.rand(3, 1)

# sigmoid activation function and derivative for updating weights
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

df["bias"] = np.ones(df["x1"].shape)
inputs = df[["x1", "x2", "bias"]]
correct_outputs = df["y"].values.reshape(4, 1)

In [183]:
weights

array([[0.04491027],
       [0.81060365],
       [0.65286615]])

In [184]:
##### Your Code Here #####

for iteration in range(10000):
    weighted_sum = np.dot(inputs, weights)
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(activated_output)

    # update weights
    weights += np.dot(inputs.T, adjustments)

print(weights)
print(activated_output) 

[[-11.83929891]
 [-11.83929891]
 [ 17.80781313]]
[[0.99999998]
 [0.99744823]
 [0.99744823]
 [0.00281301]]


In [248]:
ws = np.dot(inputs, weights)
ao = sigmoid(ws)
weights

array([[-11.83929891],
       [-11.83929891],
       [ 17.80781313]])

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [186]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer
X = diabetes.drop(columns=["Outcome"])
y = diabetes["Outcome"]

In [0]:
transformer = Normalizer()
transformer.fit(X)
X = transformer.transform(X)

In [315]:
X

array([[0.03355237, 0.82762513, 0.40262844, ..., 0.18789327, 0.00350622,
        0.27960308],
       [0.008424  , 0.71604034, 0.55598426, ..., 0.22407851, 0.00295683,
        0.26114412],
       [0.04039768, 0.92409698, 0.32318146, ..., 0.11765825, 0.00339341,
        0.16159073],
       ...,
       [0.02691539, 0.65135243, 0.38758161, ..., 0.14103664, 0.00131885,
        0.16149234],
       [0.00665306, 0.83828547, 0.39918356, ..., 0.20025708, 0.00232192,
        0.31269379],
       [0.00791454, 0.73605211, 0.55401772, ..., 0.24060198, 0.00249308,
        0.18203439]])

In [213]:
# how to add a column to array (sort of)
a = np.zeros((2, 2))
b = np.ones((2, 3))
b[:, :-1] = a

array([[0., 0., 1.],
       [0., 0., 1.]])

In [0]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / np.exp(-x)
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        # add dummy bias column
        bias_matrix = np.ones((X.shape[0], X.shape[1] + 1))
        bias_matrix[:, :-1] = X
        X = bias_matrix
        y = y.values.reshape(X.shape[0], 1) 


        # Randomly Initialize Weights
        self.weights = np.random.rand(X.shape[1], 1)

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights)

            # Activate!
            activated_output = sigmoid(weighted_sum)

            # Cac error
            error = y - activated_output
            adjustments = error * sigmoid_derivative(activated_output)

            # Update the Weights
            self.weights += np.dot(X.T, adjustments)
        return self
            
    def predict(self, X):
        """Return class label after unit step"""
        # add dummy bias column
        bias_matrix = np.ones((X.shape[0], X.shape[1] + 1))
        bias_matrix[:, :-1] = X
        X = bias_matrix
        
        # weighted sum
        ws = np.dot(X, self.weights)
        
        # activated output
        ao = sigmoid(ws)
        
        return np.where(ao >= 0.99, 1, 0)

In [356]:
from sklearn.metrics import accuracy_score
clf = Perceptron(niter=7000)
clf.fit(X, y)
clf.predict(X)

y_true = diabetes["Outcome"]
y_pred = clf.predict(X)

accuracy_score(y_true, y_pred)

0.6510416666666666

In [345]:
from sklearn.linear_model import Perceptron

p = Perceptron(max_iter=5000)
p.fit(X, y)
p.predict(X)

y_true = diabetes["Outcome"]
y_pred = p.predict(X)

accuracy_score(y_true, y_pred)

0.50390625

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?